"use client";

import { useState } from "react";
import Link from "next/link";
import { ChevronDown, ChevronUp, Bot, Calculator, MapPin, Shield } from "lucide-react";

const FAQS = [
  {
    q: "Is Grey Advisor free to use?",
    a: "Yes — Grey Advisor is completely free for all core features including the AI concierge, map search, EMI calculator, AVM valuation, and market trends. We may introduce a premium tier for power users in future.",
  },
  {
    q: "Are the property listings RERA verified?",
    a: "We recommend only RERA-registered projects. The illustrative RERA IDs generated by our AI concierge are for guidance only — always verify on your state's official RERA portal (e.g., rera.maharashtra.gov.in) before investing.",
  },
  {
    q: "How accurate is the AI property valuation (AVM)?",
    a: "Our AVM provides directional estimates based on micro-market data, builder rep, and comparable transactions. Accuracy is typically within 10-15% of market value. For a definitive valuation, consult a registered valuer.",
  },
  {
    q: "Can I use Grey Advisor for rental property analysis?",
    a: "Absolutely. Ask the AI concierge about gross rental yield, net rental yield, GRM, or rental demand for any area. The Portfolio page also lets you track rental income.",
  },
  {
    q: "Is my WhatsApp number shared?",
    a: "No. When you click 'Book Site Visit', you are redirected to WhatsApp with a pre-filled message. We do not store or access your WhatsApp account.",
  },
  {
    q: "What cities does Grey Advisor cover?",
    a: "Mumbai, Pune, Bangalore, Hyderabad, and Delhi NCR. We're expanding to Chennai and Ahmedabad soon.",
  },
  {
    q: "How do I calculate LTCG tax on my property?",
    a: "Ask the Grey AI concierge directly! Type something like 'Calculate LTCG if I bought at ₹60L in 2019 and sell at ₹1.1Cr today'. Our financial model applies the post-July 2024 rules (12.5% flat, no indexation).",
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`bg-white rounded-xl border transition-all ${open ? "border-amber-200 shadow-sm" : "border-stone-100"}`}>
      <button
        onClick={() => setOpen((p) => !p)}
        className="w-full flex items-center justify-between text-left p-5 gap-4"
      >
        <span className="text-sm font-semibold text-stone-900">{q}</span>
        {open ? <ChevronUp size={16} className="text-amber-700 flex-shrink-0" /> : <ChevronDown size={16} className="text-stone-400 flex-shrink-0" />}
      </button>
      {open && (
        <div className="px-5 pb-5">
          <p className="text-sm text-stone-600 leading-relaxed">{a}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQPage() {
  return (
    <div className="min-h-[calc(100vh-3.5rem)] bg-stone-50">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-14">
        <div className="mb-10 text-center">
          <p className="text-xs font-semibold tracking-widest text-amber-700 uppercase mb-2">Help</p>
          <h1 className="text-3xl sm:text-4xl font-bold text-stone-900 mb-3">Frequently Asked Questions</h1>
          <p className="text-stone-500">Everything you need to know about Grey Advisor.</p>
        </div>

        <div className="space-y-3 mb-10">
          {FAQS.map((faq) => <FAQItem key={faq.q} {...faq} />)}
        </div>

        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 text-center">
          <p className="text-stone-700 font-medium mb-3">Still have questions? Ask Grey AI directly.</p>
          <div className="flex flex-wrap gap-3 justify-center">
            <Link href="/concierge" className="flex items-center gap-2 px-5 py-2.5 rounded-full bg-amber-700 text-white text-sm font-semibold hover:bg-amber-800 transition-colors">
              <Bot size={15} /> Ask Grey AI
            </Link>
            <Link href="/contact" className="flex items-center gap-2 px-5 py-2.5 rounded-full border border-amber-300 text-amber-800 text-sm font-medium hover:bg-amber-100 transition-colors">
              Contact Support
            </Link>
          </div>
        </div>

        <div className="mt-8 grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[
            { href: "/concierge", icon: <Bot size={16} />, label: "AI Concierge" },
            { href: "/emi-calculator", icon: <Calculator size={16} />, label: "EMI Calc" },
            { href: "/map", icon: <MapPin size={16} />, label: "Map Search" },
            { href: "/rera", icon: <Shield size={16} />, label: "RERA Check" },
          ].map((item) => (
            <Link key={item.label} href={item.href} className="bg-white border border-stone-100 rounded-xl p-3 flex flex-col items-center gap-1.5 text-stone-600 hover:text-amber-700 hover:border-amber-200 transition-all text-center text-xs font-medium">
              <span className="text-amber-700">{item.icon}</span>
              {item.label}
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
